### ISSUE TITLE
Rviz2 crashed

### ISSUE THREAD

**Issue by angry-crab** [autowarefoundation/autoware_launch#143]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Rviz2 crashed for some reasons. Please let me know if others have the same issue. 

### Expected behavior

Rviz2 not crash. 

### Actual behavior

```
[ERROR] [rviz2-80]: process has died [pid 52321, exit code -11, cmd '/opt/ros/humble/lib/rviz2/rviz2 -d /home/xinyuwang/adehome/autoware/install/autoware_launch/share/autoware_launch/rviz/autoware.rviz -s /home/xinyuwang/adehome/autoware/install/autoware_launch/share/autoware_launch/rviz/image/autoware.png --ros-args -r __node:=rviz2 -p use_sim_time:=True -p wheel_radius:=0.383 -p wheel_width:=0.235 -p wheel_base:=2.79 -p wheel_tread:=1.64 -p front_overhang:=1.0 -p rear_overhang:=1.1 -p left_overhang:=0.128 -p right_overhang:=0.128 -p vehicle_height:=2.5 -p max_steer_angle:=0.7'].
```

### Steps to reproduce

Follow the steps of [rosbag-replay-simulation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/)

### Versions

latest master

**Comment by xmfcx** [comment]
This is very old, if this problem occurs again, a new issue can be created.
