### ISSUE TITLE
The obstacle avoidance marker is busy by default

### ISSUE THREAD

**Issue by yukkysaito** [autowarefoundation/autoware_launch#20]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

The obstacle avoidance marker is busy by default.
![image](https://user-images.githubusercontent.com/8327598/161549279-dbc03f4e-826b-4c23-a187-d24f6bfd936b.png)
In TIER IV, The fix for the obstacle avoidance marker has been incorporated but not in the awf repository.

### Purpose

The debug visualization is turned off by default, for easier to see.

### Possible approaches

modify rviz config

### Definition of done

The debugging visualization in avoidance is turned off.
![image](https://user-images.githubusercontent.com/8327598/161549379-cd3a0d70-66e2-443d-ae1b-8afcc9c2f900.png)

**Comment by takayuki5168** [comment]
I will.
Just apply autoware.rviz change in the PR link to autowarefoundation/autoware_launch
https://github.com/tier4/autoware_launch/commit/57df3eb25118bddfd093bda847e1da1383643f70

**Comment by takayuki5168** [comment]
Fixed by https://github.com/autowarefoundation/autoware.universe/pull/945
