### ISSUE TITLE
`tier4_simulated_clock_rviz_plugin` does not work with `planning_simulator.launch.xml`

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware_launch#293]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

It seems Rviz is not configured properly when `planning_simulator.launch.xml` is used (it's maybe the same for the `logging_simulator.launch.xml` too):

![image](https://user-images.githubusercontent.com/18645627/231698202-16b2e379-eb7e-42af-9296-eea797dda4db.png)

As you can see, in Rviz "ROS time" is actually wall time.
One consequence is that the `SimulatedClockPanel` does not work.

A simple workaround is to start rviz in a separate terminal like this:
```bash
$ ros2 run rviz2 rviz2 -d src/launcher/autoware_launch/autoware_launch/rviz/autoware.rviz  --ros-args -p use_sim_time:=true
```

![image](https://user-images.githubusercontent.com/18645627/231698956-c5755c0d-1067-4868-80c4-8231bda21903.png)

Then the `SimulatedClockPanel` works just fine.

I am wondering what is the proper fix though. I thought the `global_params.launch.py` should set the parameter for every Ros2 node, but apparently it is not the case.

### Expected behavior

Rviz is started with simulated clock

### Actual behavior

not the case

### Steps to reproduce

run the planning simulator

**Comment by maxime-clem** [comment]
When launching with the following command, the `use_sim_time` should be applied to all nodes (including `rviz`).
```
ros2 launch autoware_launch planning_simulator.launch.xml map_path:="$MAP" vehicle_model:="$VEHICLE" sensor_model:="$SENSOR" use_sim_time:=true
```
This is how I launch autoware when I want to use the simulated clock.

**Comment by VRichardJP** [comment]
Oh sorry, I read was using `planning_simulator.launch.xml` while reading the code of `logging_simulator.launch.xml` ^^
The `use_sim_time` works indeed!
