### ISSUE TITLE
set default vehicle/sensor?

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware_launch#767]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Autoware has only 1 sample vehicle and sensor kit, so why not make them defaults vehicle and sensor models in the launch file?

```xml
  <arg name="vehicle_model" default="sample_vehicle" description="vehicle model name"/>
  <arg name="sensor_model" default="sample_sensor_kit" description="sensor model name"/>
```

Alternatively, these variables could be set using environment variables:

```xml
  <arg name="vehicle_model" default="$(env VEHICLE_MODEL)" description="vehicle model name"/>
  <arg name="sensor_model" default="$(env SENSOR_MODEL)" description="sensor model name"/>
```

Where the environment would be set with a script like this:
```bash
AUTOWARE_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source ${AUTOWARE_DIR}/install/setup.bash

export VEHICLE_MODEL=sample_vehicle
export SENSOR_MODEL=sample_sensor_kit

# ROS stuff
# export RCUTILS_...
# export ROS_LOCALHOST_ONLY=1

# DDS stuff
# export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
# export CYCLONEDDS_URI=file://${AUTOWARE_DIR}/cyclonedds.xml
```

Actually the latter solution is something we have been using internally for a while. But even without overengineering things to much, I think there is no drawback with the first proposal (hardcoded default vehicle/sensor)

### Purpose

win 5 seconds whenever I launch autoware from command line.

### Possible approaches

- set default vehicle/sensor to sample ones
- or set default to environment variables, and provide script to source instead of `install/setup.bash`

### Definition of done

don't have to type `vehicle_model:=xxx` anymore

**Comment by xmfcx** [comment]
I am also working on:
- https://github.com/xmfcx/one_launch

to achieve a similar result but this is also a good step in the right direction.

**Comment by xmfcx** [comment]
Closing as
- https://github.com/autowarefoundation/autoware_launch/pull/768
is merged, thanks @VRichardJP !
