### ISSUE TITLE
Autoware uses Wall Time for simulation instead of ROS time

### ISSUE THREAD

**Issue by yoepav** [autowarefoundation/autoware_launch#932]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I'm using Simcenter PreScan as a simulation environment for Autoware. Simcenter uses Simulink to publish it's simulation time onto the clock topic. Autoware shows this simulation time as the ROS time, but uses the system's wall time instead of the ROS time. 

Within the autoware.launch.xml I made sure that use_sim_time equals true. When launching Autoware is also make sure to open a second terminal in which I input: `ros2 run prescan_transformer prescan_node -ros-args -p use_sime_time:='true'`.

The Autoware launch terminal then gives me warnings on multiple nodes in the form of: 
```
[WARN] [shows wall time] [node]: Lookup would require extrapolation into the past. Requested time Prescan simulation time but the earliest data is at time Wall time, when looking up transform from frame [map] to frame [base_link]
```
### Expected behavior

Autoware should use the ROS time instead of the wall time

### Actual behavior

Autoware uses wall time instead of ROS time

### Steps to reproduce

1. In Simulink make a block diagram that uses the simulink simulation time and publishes it to /prescan/clock and /clock
2. Adjust the autoware.launch.xml to make sure use_sim_time equals true
3. Launch Autoware in a terminal
4. In a second terminal input: os2 run prescan_transformer prescan_node -ros-args -p use_sime_time:='true'
5. Set a 2D pose estimate
6. Set a 2D goal pose

### Versions

- OS: Ubuntu 22.04.3
- ROS 2: Humble
- Autoware: main branch

**Comment by maxime-clem** [comment]
Thank you for opening the issue.
Can you share your full log ? It would be useful to see which nodes throw the error message.
I would also be interested in seeing a recording of the `/clock` topic as well.

**Comment by yoepav** [comment]
This is a snippet from the clock topic:
<details> 
<summary>clock topic</summary>
$ ros2 topic echo /clock
clock:
  sec: 6458
  nanosec: 590000000
---
clock:
  sec: 6458
  nanosec: 600000000
---
clock:
  sec: 6458
  nanosec: 610000000
---
clock:
  sec: 6458
  nanosec: 619999999
---
clock:
  sec: 6458
  nanosec: 630000000
---
clock:
  sec: 6458
  nanosec: 640000000
---
clock:
  sec: 6458
  nanosec: 650000000
---
clock:
  sec: 6458
  nanosec: 659999999
---
clock:
  sec: 6458
  nanosec: 670000000
---
clock:
  sec: 6458
  nanosec: 680000000
---
clock:
  sec: 6458
  nanosec: 690000000
---
clock:
  sec: 6458
  nanosec: 699999999
---
clock:
  sec: 6458
  nanosec: 710000000
---
clock:
  sec: 6458
  nanosec: 720000000
---
clock:
  sec: 6458
  nanosec: 730000000
---
clock:
  sec: 6458
  nanosec: 739999999
---
clock:
  sec: 6458
  nanosec: 750000000
---
clock:
  sec: 6458
  nanosec: 760000000
---
clock:
  sec: 6458
  nanosec: 770000000
---
clock:
  sec: 6458
  nanosec: 779999999
---
clock:
  sec: 6458
  nanosec: 789999999
---
clock:
  sec: 6458
  nanosec: 800000000
---
clock:
  sec: 6458
  nanosec: 810000000
---
clock:
  sec: 6458
  nanosec: 819999999
---
clock:
  sec: 6458
  nanosec: 829999999
---
clock:
  sec: 6458
  nanosec: 840000000
---
clock:
  sec: 6458
  nanosec: 850000000
---
clock:
  sec: 6458
  nanosec: 860000000
---
clock:
  sec: 6458
  nanosec: 869999999
---
clock:
  sec: 6458
  nanosec: 880000000
---
clock:
  sec: 6458
  nanosec: 890000000
---
clock:
  sec: 6458
  nanosec: 900000000
</details>

This is a snippet from the nodes that throw error warnings:
<details>
<summary>log</summary>
[multi_object_tracker-45] [WARN] [1711018433.197505274] [multi_object_tracker]: Lookup would require extrapolation into the past.  Requested time 6354.720000 but the earliest data is at time 1711018423.191663, when looking up transform from frame [map] to frame [base_link]
[multi_object_tracker-45] [WARN] [1711018433.693168002] [multi_object_tracker]: Lookup would require extrapolation into the past.  Requested time 6355.220000 but the earliest data is at time 1711018423.692968, when looking up transform from frame [map] to frame [base_link]
[multi_object_tracker-45] [WARN] [1711018434.198563753] [multi_object_tracker]: Lookup would require extrapolation into the past.  Requested time 6355.720000 but the earliest data is at time 1711018424.191686, when looking up transform from frame [map] to frame [base_link]
[multi_object_tracker-45] [WARN] [1711018434.694941029] [multi_object_tracker]: Lookup would require extrapolation into the past.  Requested time 6356.220000 but the earliest data is at time 1711018424.701508, when looking up transform from frame [map] to frame [base_link]
[dummy_perception_publisher_node-41] [WARN] [1711018435.148648419] [simulation.dummy_perception_publisher]: Lookup would require extrapolation into the past.  Requested time 6356.670000 but the earliest data is at time 1711018425.150246, when looking up transform from frame [map] to frame [base_link]
[multi_object_tracker-45] [WARN] [1711018435.200403781] [multi_object_tracker]: Lookup would require extrapolation into the past.  Requested time 6356.720000 but the earliest data is at time 1711018425.201290, when looking up transform from frame [map] to frame [base_link]
[component_container-34] [INFO] [1711018435.473367641] [control.trajectory_follower.controller_node_exe]: Waiting for trajectory.
[component_container_mt-35] [INFO] [1711018435.661817208] [default_ad_api.node.operation_mode]: control, planning, perception component state is unhealthy. Autonomous is not available.
[multi_object_tracker-45] [WARN] [1711018435.697144338] [multi_object_tracker]: Lookup would require extrapolation into the past.  Requested time 6357.220000 but the earliest data is at time 1711018425.700128, when looking up transform from frame [map] to frame [base_link]
[component_container-34] [INFO] [1711018435.893369823] [control.trajectory_follower.controller_node_exe]: Control is skipped since input data is not ready.
[multi_object_tracker-45] [WARN] [1711018436.192965041] [multi_object_tracker]: Lookup would require extrapolation into the past.  Requested time 6357.720000 but the earliest data is at time 1711018426.200794, when looking up transform from frame [map] to frame [base_link]
[multi_object_tracker-45] [WARN] [1711018436.698680027] [multi_object_tracker]: Lookup would require extrapolation into the past.  Requested time 6358.220000 but the earliest data is at time 1711018426.701014, when looking up transform from frame [map] to frame [base_link]
[multi_object_tracker-45] [WARN] [1711018437.194530122] [multi_object_tracker]: Lookup would require extrapolation into the past.  Requested time 6358.720000 but the earliest data is at time 1711018427.192323, when looking up transform from frame [map] to frame [base_link]
[multi_object_tracker-45] [WARN] [1711018437.699843702] [multi_object_tracker]: Lookup would require extrapolation into the past.  Requested time 6359.220000 but the earliest data is at time 1711018427.701108, when looking up transform from frame [map] to frame [base_link]
[component_container-34] [INFO] [1711018437.931929426] [control.trajectory_follower.lane_departure_checker_node]: waiting for reference_trajectory msg...
[component_container_mt-29] [INFO] [1711018438.065836816] [planning.scenario_planning.lane_driving.behavior_planning.behavior_path_planner]: waiting for dynamic_object
[multi_object_tracker-45] [WARN] [1711018438.197410599] [multi_object_tracker]: Lookup would require extrapolation into the past.  Requested time 6359.720000 but the earliest data is at time 1711018428.191187, when looking up transform from frame [map] to frame [base_link]
</details>

**Comment by yoepav** [comment]
Also this is the topic info for /tf:
<details>
<summary>log</summary>
$ ros2 topic info -v /tf
Type: tf2_msgs/msg/TFMessage

Publisher count: 2

Node name: Prescan_transformer
Node namespace: /
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: PUBLISHER
GID: 01.10.79.cd.3a.79.7d.76.e0.b8.7f.29.00.00.1c.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (10)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: robot_state_publisher
Node namespace: /
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: PUBLISHER
GID: 01.10.c9.bb.3f.17.29.c6.02.aa.b5.dd.00.00.16.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Subscription count: 17

Node name: transform_listener_impl_7ab66801fe08
Node namespace: /planning/scenario_planning/lane_driving/behavior_planning
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.01.bd.0f.88.21.fd.92.6d.9a.27.00.00.b6.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_79152000eff0
Node namespace: /planning/scenario_planning/lane_driving/motion_planning
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.0b.38.fa.da.a8.de.01.13.f9.74.00.00.4d.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_7914fc088d00
Node namespace: /planning/scenario_planning/lane_driving/motion_planning
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.0b.38.fa.da.a8.de.01.13.f9.74.00.00.8a.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_5733fcdf7c28
Node namespace: /simulation
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.0f.09.0d.47.f9.38.df.14.71.bf.00.00.19.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_63ec9239e290
Node namespace: /planning/mission_planning
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.14.f2.38.ac.9d.a6.68.46.09.eb.00.00.23.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_79d41851d8e8
Node namespace: /planning/scenario_planning/parking
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.1a.69.dd.f4.41.af.c2.44.60.73.00.00.22.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_79d42c007820
Node namespace: /planning/scenario_planning/parking
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.1a.69.dd.f4.41.af.c2.44.60.73.00.00.45.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_58942606b510
Node namespace: /
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.30.f8.fa.78.5c.e4.bd.62.14.15.00.00.19.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_62b25f0ab280
Node namespace: /perception/object_recognition/prediction
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.34.8e.93.9a.20.0b.c7.6b.6d.3e.00.00.19.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_651afb7b20a0
Node namespace: /planning
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.56.6e.51.19.0e.88.f5.d2.ac.a1.00.00.1e.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_59cb524fe838
Node namespace: /perception/traffic_light_recognition/camera6/classification
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.70.35.76.fe.cb.53.81.a2.ad.a8.00.00.19.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_63aa8711a0f0
Node namespace: /perception/object_recognition/tracking
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.8e.16.e7.49.a9.d9.74.f2.6f.b3.00.00.19.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_5b86067c8dd8
Node namespace: /default_ad_api/helpers
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.9d.43.dc.2c.fe.ed.e0.b6.1d.da.00.00.19.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_5e4ed2b1a5c8
Node namespace: /simulation
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.a0.ba.66.8d.dd.04.a8.5e.83.e7.00.00.19.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_60f0f8c14c30
Node namespace: /occupancy_grid_map
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.bb.d3.02.f1.90.39.fc.95.6f.72.00.00.26.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: transform_listener_impl_60f0f8beb9d0
Node namespace: /occupancy_grid_map
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.bb.d3.02.f1.90.39.fc.95.6f.72.00.00.3b.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (100)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: topic_state_monitor_transform_map_to_base_link
Node namespace: /system
Topic type: tf2_msgs/msg/TFMessage
Endpoint type: SUBSCRIPTION
GID: 01.10.db.64.c5.78.02.84.10.07.4a.01.00.00.17.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (1)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite
</details>

**Comment by maxime-clem** [comment]
Thank you for sharing more details.
Correct me if I am wrong, but it looks like the warning come exclusively from the `multi_object_tracker`. If so, we should investigate if there is any issue in that node with how the times are handled.

**Comment by yoepav** [comment]
I agree with you that the warning exclusively comes from multi_object_tracker, but what I find strange is that the multi_object_tracker wants to use the wall time. Something that springs to mind for me is that I have two publishers on the tf topic, thus maybe I need to disable robot_state_publisher.
